[package]
name = "cli"
version = "0.1.4"
authors = ["Seb <thesicrs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
